//
// Created by Hengruo Zhang on 2/25/20.
//

#ifndef RUNESIM_COMMON_EVENT_TYPE_H
#define RUNESIM_COMMON_EVENT_TYPE_H

#endif //RUNESIM_COMMON_EVENT_TYPE_H

enum class EventType {
  ROUND_START,
  ROUND_END,
  SUMMON,
  DIE,
  ATTACK,
  BLOCK,
  GET_HURT,
  ENLIGHTEN,
  USE_MANA,
  CAST_SPELL
};