import ujson as json

data1 = json.load(open("set1-en_us.json"))
data2 = json.load(open("set2-en_us.json"))
data = data1 + data2

initiator_h = ['''//
// Generated by Python
//

#ifndef RUNESIM_INITIATOR_H
#define RUNESIM_INITIATOR_H

''']

for id, item in enumerate(data):
    initiator_h.append("// void init{}();\n".format(item['cardCode']))

initiator_h.append("#endif //RUNESIM_INITIATOR_H")

cf = open("../src/cardset/initiator.h", 'w')
cf.writelines(initiator_h)
